[package]
name = "oc-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
unicode-width = "0.2"
oc-schema = { version = "0.1", path = "../oc-schema" }
oc-client = { version = "0.1", path = "../oc-client" }
oc-core = { version = "0.1", path = "../oc-core" }
oc-util = { version = "0.1", path = "../oc-util" }
oc-session = { version = "0.1", path = "../oc-session" }

ratatui = "0.29"
crossterm = { version = "0.28", features = ["events"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
