[package]
name = "oc-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "opencode"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
async-trait = "0.1"
oc-schema = { version = "0.1", path = "../oc-schema" }
oc-util = { version = "0.1", path = "../oc-util" }
oc-config = { version = "0.1", path = "../oc-config" }
oc-database = { version = "0.1", path = "../oc-database" }
oc-core = { version = "0.1", path = "../oc-core" }
oc-provider = { version = "0.1", path = "../oc-provider" }
oc-llm = { version = "0.1", path = "../oc-llm" }
oc-plugin = { version = "0.1", path = "../oc-plugin" }
oc-mcp = { version = "0.1", path = "../oc-mcp" }
oc-tool = { version = "0.1", path = "../oc-tool" }
oc-session = { version = "0.1", path = "../oc-session" }
oc-session-runner = { version = "0.1", path = "../oc-session-runner" }
oc-acp = { version = "0.1", path = "../oc-acp" }
oc-server = { version = "0.1", path = "../oc-server" }
oc-client = { version = "0.1", path = "../oc-client" }
oc-command = { version = "0.1", path = "../oc-command" }
oc-project = { version = "0.1", path = "../oc-project" }
oc-sync = { version = "0.1", path = "../oc-sync" }
oc-tui = { version = "0.1", path = "../oc-tui" }
tokio = { workspace = true }
clap = { version = "4.6.5", features = ["derive"] }
clap_complete = "4.6.0"
reqwest = { workspace = true }
chrono = { workspace = true }
directories = { workspace = true }
base64 = "0.23.1"
bytes = "1.12.1"
mime_guess = "2.0.5"
url.workspace = true
libc = "0.2"
tar = "0.4"
flate2 = "1"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
