[package]
name = "oc-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
oc-schema = { version = "0.1", path = "../oc-schema" }
oc-util = { version = "0.1", path = "../oc-util" }
oc-core = { version = "0.1", path = "../oc-core" }
tokio = { workspace = true }
quick-js.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
libquickjs-sys = { version = "0.1", default-features = true }
directories = { workspace = true }
url = { workspace = true }
tar = "0.4"
flate2 = "1"
semver = "1"
indexmap = { workspace = true }
once_cell = "1"
