[package]
name = "oc-project"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
sha1 = "0.10"
sha2 = "0.10"
rand = "0.8"
oc-schema = { version = "0.1", path = "../oc-schema" }
oc-util = { version = "0.1", path = "../oc-util" }
oc-core = { version = "0.1", path = "../oc-core" }
