[package]
name = "oc-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
url = { workspace = true }
chrono = { workspace = true }
directories = { workspace = true }
oc-schema = { version = "0.1", path = "../oc-schema" }
oc-util = { version = "0.1", path = "../oc-util" }
oc-core = { version = "0.1", path = "../oc-core" }
oc-mcp = { version = "0.1", path = "../oc-mcp" }
oc-plugin = { version = "0.1", path = "../oc-plugin" }
oc-llm = { version = "0.1", path = "../oc-llm" }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3"
