[package]
name = "oc-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
indexmap = { workspace = true }
url = { workspace = true }
getrandom = "0.2"
glob = "0.3"
sha1 = "0.10"
sha2 = "0.10"
regex = { workspace = true }
oc-schema = { version = "0.1", path = "../oc-schema" }
oc-util = { version = "0.1", path = "../oc-util" }
oc-config = { version = "0.1", path = "../oc-config" }
oc-database = { version = "0.1", path = "../oc-database" }
