[package]
name = "oc-util"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
indexmap = { workspace = true }
libc = "0.2"
