[package]
name = "oc-database"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
oc-schema = { version = "0.1", path = "../oc-schema" }
oc-util = { version = "0.1", path = "../oc-util" }
tokio = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled", "chrono", "serde_json", "serialize", "load_extension"] }
chrono = { workspace = true }
directories = { workspace = true }
